// <auto-generated />
namespace v2proCode.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newStudent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newStudent));
        
        string IMigrationMetadata.Id
        {
            get { return "202007281530207_newStudent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
